name: Compare Repositories

on:
  schedule:
    # Runs every Monday at 00:00 UTC
    - cron: '0 0 * * MON'
  workflow_dispatch:  # Add this to enable manual triggers

jobs:
  compare:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Add permissions to write to the repository

    steps:
      - name: Checkout Repository A
        uses: actions/checkout@v2
        with:
          repository: Telegram-Mini-Apps/TelegramUI  # Fixed repository format
          path: repoA

      - name: Checkout Repository B
        uses: actions/checkout@v2
        with:
          repository: ccddzzw/TelegramUI-vue  # Fixed repository format
          path: repoB
          token: ${{ secrets.GITHUB_TOKEN }}  # Add token for authentication
          fetch-depth: 0  # Fetch all history

      - name: Compare Directory Names
        run: |
          # List only directories recursively in src/components
          DIRS_A=$(find repoA/src/components -type d -not -path "repoA/src/components" -printf "%P\n")
          echo "Directories in repoA/src/components:"
          echo "$DIRS_A"

          DIRS_B=$(find repoB/src/components -type d -not -path "repoB/src/components" -printf "%P\n")
          echo "Directories in repoB/src/components:"
          echo "$DIRS_B"

          # Find directories in repoA/src/components that are not in repoB/src/components
          DIFF_DIRS=$(comm -13 <(echo "$DIRS_A" | sort) <(echo "$DIRS_B" | sort))

          echo "Directories missing in repoB/src/components:"
          echo "$DIFF_DIRS"

          # Check if there are differences and update README.md if so
          if [ -n "$DIFF_DIRS" ]; then
            echo "Differences found:" > repoB/README.md
            echo "$DIFF_DIRS" >> repoB/README.md
            echo "Updated README.md with differences."
          else
            echo "No differences found."
          fi

      - name: Commit Changes
        run: |
          cd repoB
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README.md with differences from repoA" || echo "No changes to commit"

      - name: Push Changes
        working-directory: repoB  # Set working directory
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ccddzzw/TelegramUI-vue.git
          git push origin HEAD:main

