name: Compare Repositories

on:
  schedule:
    # Runs every Monday at 00:00 UTC
    - cron: '0 0 * * MON'
  workflow_dispatch:  # Add this to enable manual triggers

jobs:
  compare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository A
        uses: actions/checkout@v2
        with:
          repository: Telegram-Mini-Apps/TelegramUI  # Fixed repository format
          path: repoA

      - name: Checkout Repository B
        uses: actions/checkout@v2
        with:
          repository: TownSquareXYZ/TelegramUI-vue  # Fixed repository format
          path: repoB

      - name: Compare Directory Names
        run: |
          echo "Contents of repoA/src/components:"
          ls -la repoA/src/components
          
          echo "Contents of repoB/src/components:"
          ls -la repoB/src/components

          # List all files and directories recursively in src/components
          DIRS_A=$(find repoA/src/components -type f -printf "%P\n")
          DIRS_B=$(find repoB/src/components -type f -printf "%P\n")

          # Find files in repoA/src/components that are not in repoB/src/components
          DIFF_DIRS=$(comm -13 <(echo "$DIRS_A" | sort) <(echo "$DIRS_B" | sort))

          echo "Files missing in repoB/src/components:"
          echo "$DIFF_DIRS"

          # Check if there are differences and update README.md if so
          if [ -n "$DIFF_DIRS" ]; then
            echo "Differences found:" > repoB/README.md
            echo "$DIFF_DIRS" >> repoB/README.md
            echo "Updated README.md with differences."
          else
            echo "No differences found."
          fi

      - name: Commit Changes
        run: |
          cd repoB
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add README.md
          git commit -m "Update README.md with differences from repoA" || echo "No changes to commit"

      - name: Push Changes
        run: |
          git push origin main  # Change to your main branch if needed

